### ISSUE TITLE
Configure preview command in emacs 

### ISSUE THREAD

**Issue by cassc** [ROCKTAKEY/lsp-latex#10]
Thanks for your great work!

From [texlab doc](https://texlab.netlify.app/docs/installation/previewing) I can only find examples to configure Visual Studio. How can I configure preview tool in emacs?

**Comment by ROCKTAKEY** [comment]
@cassc 
Thanks for this issue! I'm aftraid I didn't know this function, so it doesn't have the setting of it yet. 
We will add it as soon as possible, so please wait.

**Comment by ROCKTAKEY** [comment]
@cassc 
Now you can use `lsp-latex-forward-search-executable` and `lsp-latex-forward-search-args` as configuration. Then, you can do forward search with the function `lsp-latex-forward-search`.
enjoy!
