### ISSUE TITLE
use-package example

### ISSUE THREAD

**Issue by drozdziak1** [ROCKTAKEY/lsp-latex#12]
I'm trying to use this package with the `use-package` macro, but I seem to get no flycheck errors when starting lsp with texlab. Making sure I properly added the package could help me debug this problem better. Here's how I add lsp-latex to my config:
```lisp
(use-package lsp-latex
  :hook ((tex-mode . 'lsp)
	 (latex-mode . 'lsp))
  )
```

**Comment by ROCKTAKEY** [comment]
@drozdziak1
Thanks for your report. I will investigate too.

Is there any error in Emacs? If so, Please run `M-x toggle-debug-on-error` and put backtrace here.

And, is it occur if you don't use `use-package`?

**Comment by drozdziak1** [comment]
So my current problem is that with the import above I don't get `lsp-latex-build` in scope, other than that `lsp-mode` doesn't report any errors

**Comment by drozdziak1** [comment]
it somehow makes it into scope as I open `lsp-latex.el` manually, and then I get `Error processing message (json-end-of-file)` in the bottom when I call it.

**Comment by ROCKTAKEY** [comment]
@drozdziak1 
>So my current problem is that with the import above I don't get lsp-latex-build in scope, other than that lsp-mode doesn't report any errors

It is `use-pacakge` specification. You cannot use quote on cdr. You should write:
```emacs-lisp
(use-package lsp-latex
  :hook ((tex-mode . lsp)
	 (latex-mode . lsp))
  )
```
>it somehow makes it into scope as I open lsp-latex.el manually, and then I get Error processing message (json-end-of-file) in the bottom when I call it.

It might be bug. Could you eval `(setq lsp-log-io t)` and give the log in buffer like `*lsp-log: texlab2:.....*`, with error?

**Comment by ROCKTAKEY** [comment]
Bug might be fixed.

**Comment by ROCKTAKEY** [comment]
If not in your environment, please reopen this issue.
