### ISSUE TITLE
Error processing message

### ISSUE THREAD

**Issue by innerout** [ROCKTAKEY/lsp-latex#14]
Hello I have been trying to setup lsp-latex with my latex projects but I am unable to make it work.

I have been getting the message below:
```elisp
Error processing message (wrong-type-argument symbolp "-pdf")
``` 
I have tried setting `lsp-latex-build-executable` and `lsp-latex-build-args` but their values do not change.

To setup lsp-latex in my config I used the code below: 
```elisp
(use-package lsp-latex
  :ensure t
  :init
  (with-eval-after-load "LaTeX-mode"
    (add-hook 'tex-mode-hook 'lsp)
    (add-hook 'latex-mode-hook 'lsp)
    (add-hook 'LaTeX-mode-hook 'lsp)))

(use-package lsp-mode
  :ensure t
  :commands lsp
  :hook
  (scala-mode . lsp)
  (sh-mode . lsp)
  (cmake-mode . lsp)
  (LaTeX-mode . lsp)
  (yaml-mode . lsp)
  :init
  (setq lsp-diagnostic-package :flycheck)
  (setq lsp-enable-indentation nil)
  (setq lsp-enable-on-type-formatting nil)
  (setq lsp-enable-snippet t)
  (setq lsp-report-if-no-buffer t)
  (setq lsp-signature-auto-activate t)
  (setq read-process-output-max (* 1024 1024 3))
  (with-eval-after-load 'lsp-mode
    (add-hook 'lsp-mode-hook #'lsp-enable-which-key-integration)))
```
Do you know what am I missing and texlab does not work?

**Comment by ROCKTAKEY** [comment]
@innerout Thanks for your issue.
Could you run `toggle-debug-on-error` and give me the backtrace of the error?


>I have tried setting `lsp-latex-build-executable` and `lsp-latex-build-args` but their values do not change.

It is strange. I cannot understand.  
You used `setq` or `set-variable` but the value is not changed, isn't it?

**Comment by innerout** [comment]
I tried both `setq` and `set-variable` but nothing changed.
I attach the backtrace.
[error.txt](https://github.com/ROCKTAKEY/lsp-latex/files/4807841/error.txt)

**Comment by soberpeach** [comment]
I'm getting the same error with the same backtrace.

**Comment by ROCKTAKEY** [comment]
@innerout @soberpeach Thanks for your report, and I feel sorry for late reply.
`json-serialize` might be a function introduced on emacs-27, and I cannot get the function on pre-built emacs-27.
Could you tell me  Emacs version, OS, and how to get or build your emacs?

**Comment by innerout** [comment]
No worries about the small delay in the reply.
I am using the master branch version of Emacs and I am using Arch-Linux. To build my Emacs specifically, you need to use the [emacs-git](https://aur.archlinux.org/packages/emacs-git/) package in AUR.

**Comment by soberpeach** [comment]
I'm also using the [emacs-git](https://aur.archlinux.org/packages/emacs-git/) package in the AUR in Arch Linux, which is on emacs version 28.0.50. I think json-serialize was introduced in [emacs 27](https://github.com/emacs-mirror/emacs/blob/master/etc/NEWS.27).

**Comment by ROCKTAKEY** [comment]
@innerout @soberpeach  Thank you, both! 
I reproduce the bug, and I detected that its cause is " `json-serialize` cannot recognize normal list (not plist or alist) as array in json." This value should be vector. I will somehow fix it.

**Comment by ROCKTAKEY** [comment]
The bug may be fixed.
If not, please reopen this issue.
Thanks!
