### ISSUE TITLE
[Question] Format bibtex files

### ISSUE THREAD

**Issue by swarnendubiswas** [ROCKTAKEY/lsp-latex#16]
It seems `texlab` supports formatting `.bib` files. How can we use/invoke that functionality with `lsp-latex`? My `.bib` files open in `bibtex-mode`.

**Comment by ROCKTAKEY** [comment]
@swarnendubiswas Thanks for your telling me that.
Now you can use `lsp-latex`, running `lsp` on buffer with `bibtex-mode`.
Or  add to your init.el:
```emacs-lisp
(with-eval-after-load "bibtex"
 (add-hook 'bibtex-mode-hook 'lsp))
```

**Comment by ROCKTAKEY** [comment]
@swarnendubiswas  If you cannot turn on lsp-latex on bibtex, please reopen this issue.

**Comment by swarnendubiswas** [comment]
@ROCKTAKEY Thanks it works.
