### ISSUE TITLE
emacs freeze/slow

### ISSUE THREAD

**Issue by epichub** [ROCKTAKEY/lsp-latex#19]
When I open a large project (around 240 pages) with several included files, using xetex - emacs goes to 99% cpu and texlab cpu usage rises a bit - then emacs freezes/slows. Any ideas how to fix this?

**Comment by ROCKTAKEY** [comment]
Sorry for late reply. 
I've not used XeTeX, so I 'm not sure, but I think it is the problem on texlab like [this](https://github.com/latex-lsp/texlab/issues/284), which happens on Windows.
Do you use it on Windows?
If you say this problem, I'm afraid that I don't have any solutions yet.

**Comment by pfoerster** [comment]
@epichub 
Can you try `texlab 3.1.0`, please? Our latest update on the workspace analysis algorithm seems to fix the issue for some people. Note that the format of the settings has changed quite a bit though so I recommend reading https://github.com/latex-lsp/texlab/blob/master/docs/options.md first.

**Comment by ROCKTAKEY** [comment]
@pfoerster Thanks for updating!
Isp-latex now corresponds to texlab v3. texlab v3.1.0 seems to work fine as far as I use shortly. 
@epichub How is it on XeTeX?
