### ISSUE TITLE
Cannot use when open an exist file with texlab

### ISSUE THREAD

**Issue by AustinZhang1024** [ROCKTAKEY/lsp-latex#20]
When I create a new file, texlab will work correctly, but when I open an exist file with lsp, my cpu will at a full speed, Emacs won't operate anymore, Emacs costs more and more memory. Here is my config about lsp-latex:
```lisp
(use-package company
  :init  (global-company-mode)
  :bind (:map company-active-map
	      ("C-n" . company-select-next)
	      ("C-p" . company-select-previous))
  )

(use-package lsp-mode
  :hook ((latex-mode . lsp-deferred)
(tex-mode . lsp-deferred))
  :commands (lsp lsp-deferred)
  :custom
   (gc-cons-threshold 100000000)
   (read-process-output-max (* 1024 1024))
  )

(use-package lsp-ui
  )

(use-package lsp-latex
  :custom (lsp-latex-texlab-executable "D:/Software/TexLab/texlab.exe")
  )
```

**Comment by ROCKTAKEY** [comment]
I think it is the known unsolved problem of texlab on Windows (https://github.com/latex-lsp/texlab/issues/284).
I'm sorry but I don't know any solution except turning lsp-mode off, yet.

**Comment by AustinZhang1024** [comment]
> I think it is the known unsolved problem of texlab on Windows ([latex-lsp/texlab#284](https://github.com/latex-lsp/texlab/issues/284)).
> I'm sorry but I don't know any solution except turning lsp-mode off, yet.


it seems that texlab analyses other files after execute latexmk. i'm trying to execute clean automatically or you can add a function about which file (only current file) to analyse

**Comment by ROCKTAKEY** [comment]
There are all the configurations on [this page](https://texlab.netlify.app/docs/reference/configuration), but it seems to have any option about analysed files. So it might be difficult without modifying the source of texlab.exe.
I will investigate more.

**Comment by AustinZhang1024** [comment]
I have added "latexmk -c" in my compile command. Maybe we can create a issue about this under texlab. Maybe we can read about the extension's code for vscode, it works well on it

**Comment by ROCKTAKEY** [comment]
>I added "latexmk -c" in my compile command.

If you build .tex files through `lsp-latex-build`, you can add  "-c"  to `lsp-latex-build-args`.

**Comment by AustinZhang1024** [comment]
I found texlab added .aux into it too, so just delete aux file is enough. Just like `del *.aux`, or we'll not use synctex after the build.

**Comment by ROCKTAKEY** [comment]
@OdinZhang  Sorry for my late reply. Texlab is updated to v3.0.0, and freezing problem seems to be resolved. How is it work on your environment?

**Comment by AustinZhang1024** [comment]
> @OdinZhang Sorry for my late reply. Texlab is updated to v3.0.0, and freezing problem seems to be resolved. How is it work on your environment?

thanks for your reply, but I'm a little busy these days, maybe it works well on my environment, too. if there's any question, I will report you as soon as possible
