### ISSUE TITLE
using lsp-latex with orgmode for equation preview

### ISSUE THREAD

**Issue by fab6** [ROCKTAKEY/lsp-latex#24]
Hi, 
is it possible to use lsp-latex with orgmode files (or markdown files) to preview equations?
I was thinking an easy way could be
```
(add-hook 'org-mode-hook 'lsp)
```
but this was not successful!?
Fab

**Comment by ROCKTAKEY** [comment]
Texlab server cannot parse org-mode or md, so it is not possible now.
However, it should be useful, so I'd like to make it in the future.
Thanks for your great idea!

**Comment by fab6** [comment]
ok, thank you as well for your work and for your quick reply!

**Comment by ROCKTAKEY** [comment]
Close this issue because [texlab removes previewing math equation](https://github.com/latex-lsp/texlab/blob/master/CHANGELOG.md#300---2021-05-16).
