### ISSUE TITLE
Disable math preview in hover

### ISSUE THREAD

**Issue by real-or-random** [ROCKTAKEY/lsp-latex#27]
Is there some way to disable math preview when hovering?

This uses a lot of CPU on my system when the document is complex (Hundreds of math macros, complex formulas, ...) and anyway takes multiple seconds, so it's not at very helpful.

I currently have this:
```
  (setq lsp-ui-doc-enable nil)
  (setq lsp-eldoc-enable-hover nil)
```

But this disables also all the other hover stuff in latex documents (and in other languages, but that's another issue that probably can be solved with a more clever configuration).

**Comment by ROCKTAKEY** [comment]
Sorry for my late reply. Previewing is temporary deleted from texlab 3.0.0 (see https://github.com/latex-lsp/texlab/blob/a0f0dded751258f57e972ad5e2285f82e3404f27/CHANGELOG.md#changed), due to low speed.
