### ISSUE TITLE
Invalid version syntax: ‘0.exe'

### ISSUE THREAD

**Issue by jcs090218** [ROCKTAKEY/lsp-latex#28]
I am getting this error while requiring `lsp-latex`. Any idea?

```
version-to-list: Invalid version syntax: ‘0.exe' is not recognized as an internal or external command,
```

**Comment by ROCKTAKEY** [comment]
Thanks for your issue.
Could you eval this and paste message here?
```emacs-lisp
(format "exe: %s\noutput: %s"
 lsp-latex-texlab-executable
 (shell-command-to-string (format "%s --version" lsp-latex-texlab-executable)))
```

**Comment by jcs090218** [comment]
No message at all...

BTW, I am on Windows and I don't have `lsp-latex` setup now yet. Since `lsp-mode`  is actually requiring `lsp-latex` for all downstream package. I will get this error immediately after `(require 'lsp-mode)`. See

https://github.com/emacs-lsp/lsp-mode/blob/f749051fa32e9da3a81f5db4d7e45be4887b9549/lsp-mode.el#L1789-L1805

**Comment by ROCKTAKEY** [comment]
~OK, so you can download texlab from https://github.com/latex-lsp/texlab/releases.
Please download this and add to PATH or set lsp-latex-texlab-executable to file path.~

EDIT: Sorry, I misread your comment. I will deal with it immediately.

**Comment by ROCKTAKEY** [comment]
@jcs090218 Might be done. Does it work?

**Comment by jcs090218** [comment]
Work like a charm! Thank you very much! 👍
