### ISSUE TITLE
Freeze/Company Timeout 

### ISSUE THREAD

**Issue by roblem** [ROCKTAKEY/lsp-latex#30]
Possibly related to #19.

Using the latest version 3.2.0 of texlab [from here](https://github.com/latex-lsp/texlab/releases/tag/v3.2.0) on linux/Fedora 34.  Perhaps this is a texlab issue, so if I should file there, let me know.  

When I am working on a tex document completions work fine for awhile.  Sometimes it will work for 2 minutes and sometimes 10 minutes.  At some point, when I am tab completing, emacs hangs.  If I let it timeout, I get messages like this in the warnings buffer:
```
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eqr)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
Company: An error occurred in auto-begin
Company: backend company-capf error "Timeout while waiting for response.  Method: textDocument/completion" with args (candidates eq)
```
On a "real" tex file with tons of equations, references, etc., this seems to happen within 5 minutes.  I created a new tex document and as I added things to it, it finally happened but only after about 20 minutes.  

In emacs, I can restart the texlab server and it will work for awhile before it begins hanging again.

**Comment by ROCKTAKEY** [comment]
Thanks. As you say, it seems to be bug of texlab. To get log, could you eval this (after change the path) and take a reproduction? Or you can paste it on init.el and do that.
```emacs-lisp
(setq lsp-latex-texlab-executable-argument-list '("-vvvv" "--log-file" "/path/to/texlab.log"))
```

**Comment by roblem** [comment]
Here is a log.  Happened within 1 minute.  I completed some itemize environments, created a section (with label), created an equation, and then it hangs when I tried to complete `\cite`.

[texlab.log](https://github.com/ROCKTAKEY/lsp-latex/files/6778171/texlab.log)

**Comment by roblem** [comment]
Let me know if you want me to close and open an issue at texlab.

**Comment by ROCKTAKEY** [comment]
Thanks. The hung seems to occurred due to texlab hunging. 
So I'd like you to open an issue at texlab with refering this issue.

**Comment by roblem** [comment]
FYI: Got things working well addressing this issue by building the latest texlab master (https://github.com/latex-lsp/texlab/commit/45953a5c3c905acffee116287b1240c0fefb1388), so you were correct that it wasn't a lsp-latex issue.  It wasn't a texlab server issue either, it appears to be an emacs/lsp communication hang and is still being investigated.  The fix has worked for me for 5 hours straight.
