### ISSUE TITLE
Completion order and timing of <Tab> 

### ISSUE THREAD

**Issue by roblem** [ROCKTAKEY/lsp-latex#31]
This could be a `company` configuration issue, so apologies if so.  I haven't seen the strange completion behavior described below in other contexts, however.

latex command completions work fine.  Any of the reference-based completions like `cite` or `ref` have some fairly strange completion behavior.  In all the examples, I am hitting `<TAB>` at the last character in the `\ref` or `\cite` line

**Equations**

Example 1: Why aren't only `metapop` entries shown?
![completions_eq_1](https://user-images.githubusercontent.com/1871086/124911475-12c3d800-dfed-11eb-8194-496f165da42d.png)

Example 2: This is even more strange, if I only want to look at equations using the eq label I preface all equations with
![completions_eq_2](https://user-images.githubusercontent.com/1871086/124911709-5cacbe00-dfed-11eb-8718-350c1f7dfd5f.png)

Example 3: So maybe it can be narrowed down if I use `eq:`- this returns no completions
![completions_eq_3](https://user-images.githubusercontent.com/1871086/124911810-7a7a2300-dfed-11eb-98ae-cd9bf615334c.png)

**Citations**

Example 4: Just to convince myself that completions are reaching into my bibliography, here are some entries. It seems that company-prescient may be putting the cabeza one at the top as I had used it previously.
![completions_cite_1](https://user-images.githubusercontent.com/1871086/124912027-bf9e5500-dfed-11eb-9bb8-f687889373bf.png)

Example 5: But I can't narrow this list down if I start typing an author name (like Lee) no completions are returned
![completions_cite_2](https://user-images.githubusercontent.com/1871086/124912089-d5137f00-dfed-11eb-960e-91cadf4bc86c.png)

**Comment by ROCKTAKEY** [comment]
Thanks for your report and sorry for late comment. Could you attach texlab.log?
You can get it by the method on [here](https://github.com/ROCKTAKEY/lsp-latex/blob/master/.github/issue_template.md). (note: this issue template was added after you create this issue, so it is not your fault)

**Comment by roblem** [comment]
Most of the issues here are the result of using `company-prescient`.  This causes weird sorting behavior unless you set `company-prescient-sort-length-enable` to `nil` for any Tex modes as described here: https://github.com/raxod502/prescient.el/issues/86
