### ISSUE TITLE
Support for texlab.diagnostics.allowedPatterns and texlab.diagnostics.ignoredPatterns

### ISSUE THREAD

**Issue by sonofjon** [ROCKTAKEY/lsp-latex#34]
Please add support for support for texlab.diagnostics.allowedPatterns and texlab.diagnostics.ignoredPatterns.

Reference: https://github.com/latex-lsp/texlab/blob/master/docs/options.md

**Comment by ROCKTAKEY** [comment]
Thanks for your report! Now available (by https://github.com/ROCKTAKEY/lsp-latex/pull/35)!
Please use `lsp-latex-diagnostics-allowed-patterns` and `lsp-latex-diagnostics-ignored-patterns`.

**Comment by sonofjon** [comment]
Excellent! Thank you. Works perfectly.
