### ISSUE TITLE
Do not return anything for eq:, so as to allow RefTex to show the equation in the echo area

### ISSUE THREAD

**Issue by rdiaz02** [ROCKTAKEY/lsp-latex#45]
Not a bug, but a question/possible enhancement:

Since no equation preview is returned (https://github.com/ROCKTAKEY/lsp-latex/issues/24#issuecomment-1630189748), I would like for lsp-latex to do nothing on entries like `\ref{eq:n1}` because, that way, RefTeX itself can take care of displaying the equation (not as preview, but just the equation) in the echo area.  Right now, all I am returned is "Equation", which prevents my seeing RefTex's own output there.

**Comment by ROCKTAKEY** [comment]
You can allow echo area to show multiple message by `eldoc-echo-area-use-multiline-p` and `eldoc-documentation-strategy`.

**Comment by rdiaz02** [comment]
Thanks for the suggestion. 

A few additional notes, for anyone who stumbles upon this: I did not know about that (and while reading about it I stumbled upon this: https://www.masteringemacs.org/article/seamlessly-merge-multiple-documentation-sources-eldoc). 

However, the problem is that RefTeX is not using the echo area via Eldoc. So merging multiple sources will not do. (There is work in progress to have RefTeX return things via eldoc: https://karthinks.com/software/reftex-in-org-mode/#auto-preview-reference-at-point-eldoc-support with repo here: https://github.com/karthink/reftex-xref but it does not work with hl-line-mode: https://github.com/karthink/reftex-xref/issues/2 ). I guess an option would be to use eldoc-box (https://github.com/casouri/eldoc-box) but I like lsp messages in the minibuffer and this would force me to switch between the box and the echo area. 

And note that if you have `(setq lsp-ui-doc-enable t)` hovering over `\ref{eq:`  will show "Equation" as a tooltip and the equation code in the echo area; this might be good enough.

If I figure something else out, I'll add it here.

**Comment by ROCKTAKEY** [comment]
`eldoc-documentation-strategy` can also filter the strings to show.

Since even `lsp-latex` cannot detect whether the cursor is in reference to equation, so there is no other way but to suppress eldoc ad hoc.

**Comment by rdiaz02** [comment]
Thanks for the suggestion. I'll try to see if I can come of with something (I tried to play around with `eldoc-documentation-strategy` without success). Anyway, 

>  if you have (setq lsp-ui-doc-enable t) hovering over \ref{eq: will show "Equation" as a tooltip and the equation code
>  in the echo area; this might be good enough.

is, well, a possibly good enough solution for now.

Thanks, and sorry for the noise.

**Comment by ROCKTAKEY** [comment]
Here is example of a function for `eldoc-documentation-strategy`.

```emacs-lisp
(defun eldoc-documentation-default-without-equation ()
  "Same as `eldoc-documentation-default' except ignoring string matching \"Equation\"."
  (run-hook-wrapped
   'eldoc-documentation-functions
   (lambda (f)
     (let* ((default-callback (eldoc--make-callback :eager f))
            (callback (lambda (str &rest rest)
                        (unless (and str (string-match-p "Equation" str))
                          (apply default-callback str rest)))))
       (funcall f callback)))))

(setq eldoc-documentation-strategy #'eldoc-documentation-default-without-equation)
```

**Comment by rdiaz02** [comment]
Thanks. But I get a 

```
eldoc error: (wrong-number-of-arguments eldoc--make-callback 2)
```
But, please, I do not want to make you waste time on this.
