### ISSUE TITLE
BibTex not recognized

### ISSUE THREAD

**Issue by rromoli** [ROCKTAKEY/lsp-latex#49]
Hi! First of all I would thank you for the work you've done. I found a problem using `.bib` files:

```
LSP :: The following servers support current file but do not have automatic installation: texlab2
You may find the installation instructions at https://emacs-lsp.github.io/lsp-mode/page/languages.
(If you have already installed the server check *lsp-log*)
```
No `lsp-log` buffer is present 

With the same sutup I run latex files with no errors. I run GNU Emacs 29.4 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.42, cairo version 1.18.0) of 2024-07-16

**Comment by ROCKTAKEY** [comment]
~I'm sorry that I forgot prerequisite.~ [EDIT] I found that the message is displayed by `lsp-mode`, not `lsp-latex` :laughing: 

Please set `lsp-log-io` to `t`.
```emacs-lisp
(setopt lsp-log-io t)
```

**Comment by ROCKTAKEY** [comment]
I found that the message is displayed by `lsp-mode`, not `lsp-latex` :laughing:

**Comment by rromoli** [comment]
> ~I'm sorry that I forgot prerequisite.~ [EDIT] I found that the message is displayed by `lsp-mode`, not `lsp-latex` 😆
> 
> Please set `lsp-log-io` to `t`.
> 
> ```emacs-lisp
> (setopt lsp-log-io t)
> ```

This is the log:

```
Command "/home/r/.emacs.d/.cache/lsp/npm/yaml-language-server/bin/yaml-language-server --stdio" is present on the path.
Command "/home/r/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/bin/vscode-html-language-server --stdio" is present on the path.
Command "rust-analyzer" is not present on the path.
Command "perlnavigator --stdio" is not present on the path.
Command "nginx-language-server" is not present on the path.
Command "/home/r/.emacs.d/.cache/lsp/marksman/marksman" is present on the path.
Command "java -jar /home/r/.emacs.d/.cache/lsp/magik-ls/magik-language-server-0.9.0.jar --debug" is present on the path.
Command "kotlin-language-server" is not present on the path.
Command "/home/r/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/bin/vscode-json-language-server --stdio" is present on the path.
Command "elp server" is not present on the path.
Command "/home/r/.emacs.d/.cache/lsp/npm/vscode-langservers-extracted/bin/vscode-css-language-server --stdio" is present on the path.
Command "/home/r/.dotnet/tools/csharp-ls" is not present on the path.
Command "cmake-language-server" is not present on the path.
Command "clangd --header-insertion-decorators=0" is not present on the path.
Command "astro-ls --stdio" is not present on the path.

```

**Comment by ROCKTAKEY** [comment]
Re-open `.bib` file after setting `lsp-log-io`.

BTW, do you install texlab?
https://github.com/latex-lsp/texlab

**Comment by rromoli** [comment]
I have already declared the `lsp-log-io` into my init.el file, and it work for other language such as latex and R, but it doesen't work for bibtex. I have installed texlab and it works as expected with .tex files

**Comment by ROCKTAKEY** [comment]
Would you evaluate `(mapconcat #'lsp--workspace-print lsp--buffer-workspaces "][")` in the latex buffer with texlab enabled, and paste here?

If the result is `[texlab:NNN]`, `lsp-latex` is not being used, while `[texlab2:NNN]` means that `lsp-latex` is being used.

**Comment by rromoli** [comment]
The result is `"texlab:20607"`. It was my fault in the configuration, sorry for the inconvenience. I see texlab in the lsp-description and I thought it was all good. now I fixed it. texlab2 is working well and the .bib file is recognized too.

**Comment by rromoli** [comment]
thanks
