### ISSUE TITLE
Support latest release of texlab?

### ISSUE THREAD

**Issue by yanghaoxie** [ROCKTAKEY/lsp-latex#6]
`texlab` had 1.0 release https://github.com/latex-lsp/texlab/releases.

It seems like that `texlab` does not rely on `java` anymore. So, can we support this latest release?

**Comment by ROCKTAKEY** [comment]
Thank you for telling that. I've not noticed. We'll support this soon.

**Comment by ROCKTAKEY** [comment]
@yanghaoxie Support latest release :)

**Comment by yanghaoxie** [comment]
Thank for so much!:) @ROCKTAKEY
