### ISSUE TITLE
Texlab is now written in rust

### ISSUE THREAD

**Issue by PythonNut** [ROCKTAKEY/lsp-latex#7]
Due to this, I think anything referencing Java or jar files is likely to need updating.

**Comment by ROCKTAKEY** [comment]
Thank you for this issue!

Referencing Java or jar files is only for compatibility of texlab v 0.4.2 or less. If you use texlab binary v1.0.0 or more, Java or jar files is not needed. Instead, you should set `lsp-latex-texlab-executable` like:
``` emacs lisp
(setq lsp-latex-texlab-executable "/path/to/texlab")
```
or add to enviroment variable `PATH`.

In this package, you can use binary from texlab [release](https://github.com/latex-lsp/texlab/releases), newer executable file, or even older jar file.

However, this is not clear on document, so I will add.

Thanks!
