### ISSUE TITLE
Consider adding this package to lsp-mode

### ISSUE THREAD

**Issue by contrun** [ROCKTAKEY/lsp-latex#8]
I just opened a [PR](https://github.com/emacs-lsp/lsp-mode/pull/1473) in lsp-mode. Then I found your package. Your package is much more mature. Could you please consider contributing to the lsp-mode? It would be beneficial to a wider audience.

**Comment by ROCKTAKEY** [comment]
@contrun Thanks for your proposal! I'm willing to contribute lsp-mode, but I have one concern. 

How to merge this package to lsp-mode? I consider "copying file or program," or "proposing git submodule". This package is too large to be copied to"lsp-client.el", but git submodule is not ordinal. In addition, regarding git submodule, a commit on lsp-mode is needed for this package's updates. I think copying this file to lsp-mode is better choice, but perhaps it would be refused because of irregularity. What do you think about this? 

Thanks.

**Comment by contrun** [comment]
I had only submitted a few small patches in lsp-mode. So I can't really tell what lsp maintainers' opinions are. But I believe it would be best if we can follow the current code structure, i.e. create a new file named lsp-latex and follow code like  https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-erlang.el. It is my understanding that to start with, you can copy the lsp-latex.el of this project, not too much code needs to be modified. I have to say the maintainers of lsp-mode are particularly friendly. Especially @yyoncho, he's very responsive in gitter. I suggest you to contact him on gitter of the lsp-mode. Also lsp-mode is looking for additional collaborators/members  https://github.com/emacs-lsp/lsp-mode/issues/1075. Maybe you can propose to be the maintainer of lsp-latex under lsp-mode. I will be happy to answer any other questions.

**Comment by yyoncho** [comment]
@ROCKTAKEY few notes:

I checked the lsp-latex.el and I was unable to find something irregular in it, can you clarify? As @contrun mentioned you could create lsp-latex.el in lsp-mode repo. You could also onboard it to melpa, link it from lsp-mode README and support it here like `ccls` extension. In lsp-mode we have language-specific maintainers so if you want you could join the team and support lsp-latext.el as part of lsp-mode team. lsp-mode development is very open and democratic.

**Comment by ROCKTAKEY** [comment]
@contrun 
Thanks. I didn't know one-file lsp-clients are exist in lsp-mode. Isp-erlang.el is good example for me.

@yyoncho 
Sorry for my confusing. The irregular point I think is merging the file that already exist as one package, lsp-latex. 

At two:
I cannot decide which is better soon, so please give me a time.
In addition, I have a question. If my package is merged to lsp-mode or added to melpa, what will the code on the [PR](https://github.com/emacs-lsp/lsp-mode/pull/1473) written by @contrun be? will it be deleted? If so, I feel sorry.

Thanks for your time.

**Comment by yyoncho** [comment]
> If my package is merged to lsp-mode or added to melpa, what will the code on the PR written by @contrun be? will it be deleted?

If it is merged it will be deleted. If you onboard it to melpa it could either stay as a lightweight alternative or be deleted in favour of the external package. In lsp-mode the language-specific packages are maintained by language users and it is entirely up to them how to structure the integration code.

**Comment by ROCKTAKEY** [comment]
Thanks. I got it. 
If this package is merged to lsp-mode, how to update lsp-latex.el in lsp-mode?
Make PR, or commit directly?

**Comment by ROCKTAKEY** [comment]
@yyoncho @contrun 
I decided to add this package to melpa.
I made [PR](https://github.com/melpa/melpa/pull/6850) just now.
Thanks a lot!

**Comment by yyoncho** [comment]
thank you, when you are done you may link it from lsp-mode's readme.

**Comment by ROCKTAKEY** [comment]
Merged to MELPA! Thanks!
