### ISSUE TITLE
How to view the preview?

### ISSUE THREAD

**Issue by ketan0** [ROCKTAKEY/lsp-latex#9]
Thanks for making this package available!

When I mouse over anything in a tex file, a (lsp-ui-doc?) frame appears titled "preview"—mousing over it appears to display the data for an inlined image in the echo area as such:

![image](https://user-images.githubusercontent.com/36572102/80170906-140b0f80-85b7-11ea-8a1f-48ccc6d874cf.png)

Maybe a dumb question, but how do you actually view the inline preview?

**Comment by ROCKTAKEY** [comment]
@ketan0 Thanks for this issue!

My Emacs don't display that image too. 
This issue may be unsolvable because Emacs may have no base64 image decode, or may be lsp-ui-doc's bug, but I will investigate.

**Comment by ROCKTAKEY** [comment]
@ketan0 I create [PR](https://github.com/emacs-lsp/lsp-mode/pull/1612) dealing with this issue!

**Comment by ketan0** [comment]
This looks fantastic! Thanks for working on it and submitting the PR. :)

**Comment by ROCKTAKEY** [comment]
@ketan0 
The [PR](https://github.com/emacs-lsp/lsp-mode/pull/1612) is merged!
So you can view the image! Thanks!

**Comment by ketan0** [comment]
Thanks for your work on this--it displays the formula nicely now!
